### ISSUE TITLE
containner has 2 image?

### ISSUE THREAD

**Issue by WandernForte** [TissueImageAnalytics/CoNIC#12]
![b44162e710a029f3f2037b962287585](https://user-images.githubusercontent.com/81891513/154691632-b0f239fc-69fd-406b-b8a7-443b3a4f0bf4.png)
this is our submission feedback.

In my machine, when I use `./test.sh`, it can run very well.
But only `docker run` error occurs as follow,
![image](https://user-images.githubusercontent.com/81891513/154692282-c41785b2-df4e-40b8-91a7-beb15a3058e1.png)

**Comment by WinnieLaugh** [comment]
Hi, maybe you could check the path you mounted in _docker run_. I guess there were two *.mha files in the folder.

**Comment by vqdang** [comment]
Please ensure that your output folder (mounted at `/output` within the docker) contains only 1 single .mha file. This .mha must contain your task 1 prediction output.

Additionally, from the image you showed above, the mounted path for `/input` does not contain any file. Please check your setup within `test.sh`
