### ISSUE TITLE
Baseline Training Code

### ISSUE THREAD

**Issue by WinnieLaugh** [TissueImageAnalytics/CoNIC#5]
Hi TIA Group,

Thank you for holding such an amazing challenge! 

I was wondering that if you are going to release the _training code_ of the baseline checkpoint provided?  As I tried to train a HoVerNet myself and found that I could only reach:

PQ         mPQ
0.5753   0.3848

with the original training code and the new post-processing strategy(resize it to 40x resolution).

It would be more than great if you can release the _training code_ of the baseline checkpoint.  Thanks a lot!

Best Regards,
Winnie

**Comment by simongraham** [comment]
Hi!

Great to see taking part in the challenge!

We can release the training code if you would like. Note, we use the HoVer-Net code from the original repository [here](https://github.com/vqdang/hover_net). The only difference is that we use padded convolution in the decoder and therefore the output size is the same as the input size. 

Can you confirm whether you are using the exact same training / validation split that we used

**Comment by simongraham** [comment]
Hi @WinnieLaugh ,

We have now made the training code with the exact same configuration that we used for the baseline available. For this, we made a new branch in the original repository, named `conic`. 

You can find it [here](https://github.com/vqdang/hover_net/tree/conic), along with further instructions on setup and training the network.

**Comment by WinnieLaugh** [comment]
Hi @simongraham 

Thanks a lot for sharing the training code! it would definitely help a lot.

Best Regards,
