### ISSUE TITLE
Why dice value is still zero?

### ISSUE THREAD

**Issue by 13015517713** [TissueImageAnalytics/CoNIC#6]
I used the baseline code, and just update the method to upsample. I haven't changed other configurations.
When I start to train and infer model, I found the value of infer-valid-tp_dice_5 keeping zero after epoch=13(when infer). 
I don't no why.

**Comment by simongraham** [comment]
We leave it to you to try and improve the performance for the purpose of this challenge. Of course you are also more than welcome to try alternative methods and architectures.

**Comment by 13015517713** [comment]
Ok, fine.
Thanks.
