### ISSUE TITLE
relationship between PanNuke, MoNuSeg, and Lizard

### ISSUE THREAD

**Issue by EdwardZhao1991** [TissueImageAnalytics/CoNIC#9]
Dear all,

Thanks for the awesome work.

I was wondering is there any overlap between PanNuke, MoNuSeg, and Lizard?

**Comment by simongraham** [comment]
Hi!

Lizard is a dataset just consisting of images from colon tissue. We used some of the colon images from PanNuke, but without the original annotations. Instead, we generate annotations as described in the [Lizard paper.](https://arxiv.org/abs/2108.11195) You can see a more thorough breakdown of the datasets used in the paper.
